### PR TITLE
CanvasOnChain: Show the canvas with all the pixel placements #29

### LINKED ISSUE #29: CanvasOnChain: Show the canvas with all the pixel placements
Also, when the user hovers the canvas it needs to show the pixel highlight, so it's clear where is the pixel placement.

The Canvas doesn't need to be a real <canvas>, it could be anything.

(blocked by https://github.com/BuidlGuidl/batch11.buidlguidl.com/issues/28)

### PR DESCRIPTION
**Pull request by melanke**
## Description

- Changes on the PixelCanvas contract to fix the intialization script and iimplements a new method to retrieve all the pixels at once.
- Presents the pixels retrieved from the contract.
- ~~Changes the scaffold config to use hardhat, otherwise the next:type-check would fail because the contract is not deployed yet.~~
- Fixes the deploy script to keep the BatchRegistry deployment
- ⚠️Disclaimer: This PR is based on [Abidoyesimze](https://github.com/Abidoyesimze)'s PR, which is still open, so you will see his changes too.

image

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

Closes #29

Your ENS/address:
0x2Bc096A12C5b37F035180aDeF70EB2B88351e5B8

### CODE REVIEW

**Review by phipsae — CHANGES_REQUESTED** [review]
@melanke, please exclude all files not related to this PR (all hardhat, etc.).
I understand you needed them for testing, but make sure to remove them before pushing to github. 

Thanks!

**Comment by melanke** [comment]
@phipsae done, I've removed scaffold.config form the commit. But because of this I had to commit with --no-verify flag.

In the future it might be interesting to always rely on hardhat locally, instead of optimism, and use .env variables to control scaffold.config's targetNetworks on different environments.

**Comment by phipsae** [comment]
> @phipsae done, I've removed scaffold.config form the commit. But because of this I had to commit with --no-verify flag.
> 
> In the future it might be interesting to always rely on hardhat locally, instead of optimism, and use .env variables to control scaffold.config's targetNetworks on different environments.

What I meant is, that in this PR there shouldn't be any files from the PR of @Abidoyesimze. 

What to you mean? Can't you change easily the network inside `scaffold.config `.

**Comment by phipsae** [comment]
Thanks! And merged

**Pull request merged**
